### ISSUE TITLE
Since uglify was introduced, a huge amount of compiler warnings occure on the console

### ISSUE THREAD

**Issue by marcusvetter** [purifycss/purifycss#104]
Since uglify was introduced, a huge amount of compiler warnings occure on the console, e.g.:

[...]
_WARN: Dropping unused function argument c [null:2,13109]
WARN: Dropping unused function argument c [null:2,12966]
WARN: Dropping unused function argument b [null:2,15188]
WARN: Dropping unused function argument state [null:114,55]
WARN: Dropping unused function argument $scope [null:1140,69]
WARN: Dropping unused function argument attributes [null:1164,77]
WARN: Dropping unused function argument element [null:1164,68]
WARN: Dropping unused function argument $scope [null:1164,60]
WARN: Side effects in initialization of unused variable HeadlineType [null:1219,20]
WARN: Dropping unused function argument modal [null:1585,23]_
[...]
     
This occures because the compress option is defaulted to true and not configurable from the outside.

Fix proposal: Make the compress option configurable; I'll provide a pull request for that.

**Comment by vanthoom** [comment]
+1
