### ISSUE TITLE
breaking change?

### ISSUE THREAD

**Issue by jasedwards** [purifycss/purifycss#109]
I am using grunt-purifycss which of course has never changed.  However, a few days ago the version of purifycss used with it was 1.0.21 and is now 1.1.3.  Somewhere in in between purifycss is now removing styles that are actually used.  Are you aware of any breaking changes or something I need to do differently with the latest release?  Thanks.  Here is an example of something that was removed:

``` css
html body header h1 button.expandMenu{
```

**Comment by kennyt** [comment]
Can you show me your file structure + the way you're passing the files to grunt-purifycss? Also, are you passing in your `index.html` file (the file that contains `html`, `body`)?

**Comment by jasedwards** [comment]
Here is my grunt config:
``` 
  src: ['<%= yeoman.dist %>/scripts/scripts.js', '<%= yeoman.dist %>/scripts/vendor.js'],
        css: ['<%= yeoman.dist %>/styles/app.css'],
        dest: '<%= yeoman.dist %>/styles/app.css'
```
The app.css is the generated bundle from cssmin.  I also tried running it before cssmin and changed yeoman.dist to yeoman.tmp but had same results.
Not passing in html but then I never have and it always worked.  Is that a newer requirement?

**Comment by kennyt** [comment]
Well, that isn't a new requirement. That's always been documented that you'd have the pass in the HTML. The reason it was working before is that the logic of determining the element selectors the app was using wasn't robust, which left a lot of the HTML element selectors in (even if it wasn't being used), which is why I suspect it was still working for you.

The version bump improved the logic and is now removing selectors for HTML elements if they aren't used. Try including all the HTML files and let me know if that fixes it

**Comment by jasedwards** [comment]
no luck.  Also a lot of styles with pseudo elements are removed.  so div.pageMenu:after{display:table,contant:""} should stay but is not.  One scenario that could be the cause of those is that the classes are referenced from the template.js that contains angularjs $templateCache.  These are bower components so there is no html file for me to pass in for those as ngtemplates has already been run for those and only the .js provided.  so instead of class="page-menu" it is class=\"page-menu\"

**Comment by kennyt** [comment]
try removing and reinstalling grunt-purifycss. I fixed a bug yesterday concerning the psuedo selectors [commit here](https://github.com/purifycss/purifycss/commit/1f890fc5e81dae9bc1bc859a74127dc609551189).

If that doesn't work, I'll look into it later tonight

**Comment by jasedwards** [comment]
that change is present.  Did a fresh install before adding my .html files

**Comment by kennyt** [comment]
Alright, try reinstalling again. I'm about 33% sure v1.1.5 will fix your problem :dizzy_face: :worried: :neutral_face: . Let me know if it doesn't

**Comment by jasedwards** [comment]
It appears that the stuff is all there with one problem though.  It seems to rewrite everything in lowercase.  For example 

``` css
html body header h1 button.expandMenu 
```
becomes 
``` css
html body header h1 button.expandmenu
```
 in the generated css.

**Comment by kennyt** [comment]
Woops. Alright :one: :heavy_plus_sign:  :watch: v1.1.6

**Comment by jasedwards** [comment]
That got it!  Thanks so much for the quick turn around

**Comment by kennyt** [comment]
Nps. Thanks for letting me know about the bug!
