### ISSUE TITLE
Question: How does this work with media queries?

### ISSUE THREAD

**Issue by kylegach** [purifycss/purifycss#114]
_Edit: I should’ve looked through the closed issues before posting. Looks like both of my questions have already been answered in the affirmative. Feel free to close/delete._

PurifyCSS seems _amazing_, but it absolutely must support media queries to be usable for me (and others, I would imagine). For example:

In the markup:
```
<div class="m-2 m-4@lg">...</div>
```

And with these styles:
```
.m-2 { margin: 1rem; }

@media (min-width:50em) {
    .m-4\@lg { margin: 4rem; }
}
```

Will PurifyCSS correctly grab the entire media block?

Also, less critical, but will my [use of the `@`](http://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further/#responsive-suffixes) trip it up, because it needs escaped in the CSS?

Thanks!

**Comment by kennyt** [comment]
it handles media queries! if all the classes inside of a media query is removed, then the media query itself is also removed
