### ISSUE TITLE
Issues when using with angular

### ISSUE THREAD

**Issue by atul-bajpai** [purifycss/purifycss#124]
purifycss removing css rules defined in the css file which are set by angular lib files. e.g
angular set the class .ng-inactive for the in-active/disable buttons./anchors as 
**d.setClass(a,"ng-inactive","ng-active")**
which purify css is removing from css.
Also, when using certain js plugins, they allow setting additional css classes through some configuration object something as follows:
{
   label: 'Name',
   id: "testId",
   ......
   className: "iconClass"
}
purify css removing these css .class and #id  rules from css

**Comment by Illyism** [comment]
Did you include the configuration objects in your content? The angular lib files should be included as well.

**Comment by atul-bajpai** [comment]
In my grunt file I am doing it likethis

purifycss: {
		    options: {
		    	minify : false,		    	
		    	info:  true, 
		    	rejected: true
		    },
		    target: {
		      src: ["../*.dev.jsp",		      		 
  	      		     "../js/*.js"],
		      css: ["../css/style.css"],
		      dest: "../dest/css/purestyles.css"
		    }
		  }

**"../js/*.js"** will this include the sub folders also ?

**Comment by Illyism** [comment]
No, it won't. You need to use `**`

**Comment by atul-bajpai** [comment]
thanks, its working.
