### ISSUE TITLE
Add whitelist to CLI

### ISSUE THREAD

**Issue by crico** [purifycss/purifycss#128]
It would be interesting to launch purifycss with whitelist from the CLI. For example:

`purifycss src/css/main.css src/css/bootstrap.css src/js/main.js --whitelist button-active *modal* --out src/dist/index.css`

**Comment by KwesiJnr** [comment]
Yes, please. When is this feature coming into CLI?

**Comment by Ffloriel** [comment]
I think this issue can be closed now.

**Comment by crico** [comment]
Perfect!

**Comment by dyingangel666** [comment]
And for those who are wondering how whitelisting with multiple classes works: Here's an more complex example ;-)

`
purifycss "./dist/**/styles.*.css" "./src/index.html" "./src/app/**/*.ts" "./src/app/**/*.html" --min --info --rejected --whitelist body* *sg-select* *sg-icon* *sg-flyout* *sg-pagination* *sg-toast* *sg-image-cropper* *cdk-* *sg-button* *sg-checkbox* *sg-input* *sg-form-field* *sg-file-loader* *sg-user-img* *transition* *dimmer* --out "./dist/"
`
