### ISSUE TITLE
Builds broken -- Uglifyjs & new release

### ISSUE THREAD

**Issue by rstoenescu** [purifycss/purifycss#159]
Hi,

Sorry for opening an issue. Didn't know any other way to contact you. I am the owner of Quasar Framework and I depend on this package on Quasar starter kit. Due to the deprecation with error on Uglifyjs devs cannot build anymore.

But I saw this commit https://github.com/purifycss/purifycss/commit/108142998959b1812365e69c6229e0c0284adedc and was wondering when an npm release with this change will be available so I can take a decision: either remove purifycss from the build or wait for the npm release.

Thank you and sorry for opening a github issue for this (but times are hard),
Razvan

**Comment by razagill** [comment]
@rstoenescu till a new release you can install it directly from the repo:

`npm i -D git+https://git@github.com/purifycss/purifycss`

**Comment by rstoenescu** [comment]
@razagill This is for Quasar starter kit and it's optional anyways. Just to make sure we are on same page: PurifyCSS is not used by Quasar, it's just added to the starter kit for apps built with Quasar as a bonus.

The problem is that I can't provide a starter kit with a non official package version because many things can break and we'll be at the mercy of the github repo :)

**Comment by razagill** [comment]
@rstoenescu ah, I thought you just wanted to have a build for your lib. Yeah, then nothing else than to wait for the official release.

**Comment by hindsc52** [comment]
Any idea when this official release will be available?

**Comment by kennyt** [comment]
I just released with updated uglify-js. Thanks for letting me know

**Comment by rstoenescu** [comment]
@kennyt Thank you for the quick turnaround!

I still have one issue now. I get an ES6 error. Is PurifyCSS transpiled to work with older nodejs version?

```
/work/quasar-template-default/template/node_modules/purify-css/lib/purifycss.js:772
const getOptions = (options = {}) => {
                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/work/quasar-template-default/template/build/css-utils.js:4:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

**Comment by Illyism** [comment]
@rstoenescu Should be fixed with the current release.

**Comment by hindsc52** [comment]
@Illyism I am getting the same error as above

```
Loading "purifycss.js" tasks...ERROR
>> SyntaxError: Use of const in strict mode.
```

using the latest version.

**Comment by Illyism** [comment]
@hindsc52  I've pushed a new update through that properly transpiles the code a few minutes ago, it's version 1.2.2

**Comment by hindsc52** [comment]
Ok, just checking against that now

**Comment by rstoenescu** [comment]
@Illyism Thank you again! 1.2.2 works as expected. :+1:

**Comment by hindsc52** [comment]
Im getting `Warning: Symbol is not defined` any ideas?

**Comment by Illyism** [comment]
@hindsc52 What version of node are you using?

**Comment by hindsc52** [comment]
@Illyism 5.4

**Comment by rstoenescu** [comment]
@hindsc52 Hi, you can disable PurifyCSS from `/config/index.js` if you are having trouble with it.
