### ISSUE TITLE
Using prepack for js file

### ISSUE THREAD

**Issue by Ffloriel** [purifycss/purifycss#168]
Purifycss is relatively simple to understand. It takes a content file, like an html file and extract all the words from it. It takes a css file and extracts all the selectors from it. Then, it compares the two.  
But this approach causes some issues for more complex situation:  
```js
const class1 = ["abc", "efg"].join("d")
```
```css
.abcdefg { background: blue; }
```
In the above example, purifycss will extract the following strings from the js:
- class1
- abc
- efg
- join
- d

That means that abcdefg is not considered used since it will not match with the array of strings that we extracted from the js.  

Prepack will transform the js before extracting strings from it.
```js
const class1 = ["abc", "efg"].join("d")
// becomes
const class1 = "abcdefg"
```

**Comment by Illyism** [comment]
Great! Thank you

**Comment by Ffloriel** [comment]
One of the reason I created this issue is because Prepack is still experimental, and choosing to use it is not a minor change. I should have said this before, sorry about that. 

In my opinion, it would be interesting to change a little bit the implementation of purifycss, using postcss to walk through the css ast and get only the selectors, and potentially a comment line https://github.com/purifycss/purifycss/issues/137.

It could be an idea for a version 2 of purifycss. It could be developed on another branch, not released to npm until it is ready.

**Comment by Illyism** [comment]
Yes. It seems usable, but the warnings are annoying and perhaps we can turn them off. I'd remove prepack for now.

**Comment by Ffloriel** [comment]
I agree. You will need to revert the changes I made for https://github.com/purifycss/purifycss/pull/169.
