### ISSUE TITLE
SyntaxError when purifying with Django templates

### ISSUE THREAD

**Issue by lopopolo** [purifycss/purifycss#172]
In the upgrade from 1.2.2 -> 1.2.3 I started getting the following errors:

```
Unexpected token (1:1)
SyntaxError
```

when attempting to purify html files that are django templates.

The templates look like this:

```django
{% extends "base.html" %}
{% load hyperbola_core_tags imagekit %}

{% block active_app %} contact {% endblock active_app %}
{% block title %} {{ block.super }} :: Contact {% endblock title %}
{% block section_title %} Contact Information {% endblock section_title %}

{% block content %}
<div class="row">
  <div class="col-md-9">
    <h1>{{ name|escape }}</h1>
    {% for contact in contacts %}
    {% ifchanged contact.type %}
    <h2>{{ contact.type.type|escape }}</h2>
    {% endifchanged %}
    <div class="row">
// snip ...
```

You can see the error in action by running `gulp` in this project: https://github.com/lopopolo/hyperbola (you might have to muck with deps)

**Comment by Ffloriel** [comment]
Thanks for the warning.

This error is caused by Prepack. Since it is not a javascript file, it causes a SyntaxError.
Purifycss should remove unused classes nonetheless. Does purifycss remove unused classes in your case?  
If not, you can use 1.2.2 by writing it in the package.json file while the bug is fixed.

**Comment by lopopolo** [comment]
I don't know exactly what is going on, but it caused a massive diff in my generated CSS.

**Comment by Ffloriel** [comment]
I think I know why. The diff must be the classnames that contains an `-`.
You can update purifycss to the most recent version (1.2.6), it should work now.

**Comment by lopopolo** [comment]
Thank you! that did the trick
