### ISSUE TITLE
Css ignored if it has not all the necessary classes for the given css selector

### ISSUE THREAD

**Issue by khalyomede** [purifycss/purifycss#204]
**Issue**

A CSS rule is being trimmed if it is not exactly contained in the html file.

**Reproduce the issue**

```javascript
console.log( purify('<div class="waves-effect waves-light"></div>', '.waves-effect.waves-light .waves-ripple { background-color: rgba(255, 255, 255, 0.45); }') );
```

**Expected value**

> .waves-effect.waves-light .waves-ripple { background-color: rgba(255, 255, 255, 0.45); }

**Actual value**

> 

**Motivation for this fix**

In CSS the selector is being applyied in this case, either by applying `waves-effect waves-light`, `waves-ripple` or `waves-effect waves-light waves-ripple`. So purify should also behave the same.

**Comment by agilan2001** [comment]
The CSS selector : `.waves-effect.waves-light .waves-ripple` selects the elements with DOM structured as :

`<div class="waves-effect waves-light">
    <div class="waves-ripple">
        This inner div is selected
    < /div>
< /div>
`


And the CSS selector : `.waves-effect.waves-light , .waves-ripple` selects the elements with DOM structured as :

`<div class="waves-effect waves-light">This div is selected</div>`

Hence, this is not actually an issue and this is worth closing !
