### ISSUE TITLE
Attribute Selectors

### ISSUE THREAD

**Issue by phreezer** [purifycss/purifycss#32]
Purify is awesome but its stripping out some code that uses attribute selectors.

I use an icon set that is created from [Icomoon](https://icomoon.io). The css file they provide uses attribute selectors like [class^="icon-"], [class*=" icon-"] which is getting stripped out.

Is it just me or are these selectors not supported?

**Comment by kennyt** [comment]
Can you please post a full example of the single CSS ruleset?

**Comment by phreezer** [comment]
[plunkr](http://plnkr.co/edit/WHIhkmjn7ox1hqxg8oXw)

It strips out the [class^="icon-"], [class*=" icon-"] block
