### ISSUE TITLE
Feature Request : MultiPage Support

### ISSUE THREAD

**Issue by surjithctly** [purifycss/purifycss#35]
This wont be perfect until it has a multi-page support. Please add that.

**Comment by kennyt** [comment]
Hmm, multi-page support. Can you expand on that? Couldn't you just call the function once per page?

**Comment by surjithctly** [comment]
What if a class is defined on one page but not on other?

eg: .blockquote is in testimonials page, but not on home page? Will that
work?

Also, Is it works directly on the server? or will it provide a purified CSS
file?

:confused:

**Comment by replete** [comment]
With gulp, you could src all the .html static pages, concatenate them into one file, and then PurifyCSS that. Of course, you'd had to strip n1+1 `<head></head>` and `<html>`.

**Comment by davidguilherme** [comment]
Look the README.md, the content and css parameters may receive a array of file paths.

And, the following test:
```javascript
// test/purify_test.js line 47
it('works with multiple files', function(){
    var content = [absPath + 'multiple_files/multiple_files.js', absPath + 'multiple_files/multiple_files.html'];
    var css = [absPath + 'multiple_files/multiple_files.css', absPath + 'multiple_files/multiple_files2.css'];
    var result = purify(content, css);

    expect(result.indexOf('.taylor-swift') > -1).to.equal(true);
    expect(result.indexOf('.blank-space') > -1).to.equal(true);
    expect(result.indexOf('.shake-it-off') === -1).to.equal(true);
  });
```
[Source](https://github.com/purifycss/purifycss/blob/master/test/purify_test.js#L47)
