### ISSUE TITLE
npm install -g ?

### ISSUE THREAD

**Issue by crazy4groovy** [purifycss/purifycss#41]
Is it possible to wrap this as a shell script? very handy if so!

**Comment by Illyism** [comment]
Yes, see #33 #37
I added support for it today, it needs a version bump, an update sent to NPM and a mention in the README.

**Comment by kennyt** [comment]
@Illyism feel free to put what you put in https://github.com/purifycss/purifycss/pull/37 in the README (without the screen shot). Put it below the 'callback' section and above the 'at build time' section
