### ISSUE TITLE
@media selectors are removed

### ISSUE THREAD

**Issue by tsimeunovic** [purifycss/purifycss#46]
After purifying using default options: {} object all @media queries got removed (although styles within them are used). Also it would be nice if templates put in $templateCache in angular are also considered (not issue just would be nice feature). Except that thanks for great product!

**Comment by kennyt** [comment]
Ah, I can fix this once I get off the bus. Just checking, I assume that you had ids or html tags in that media query? Or did it include classes also?

**Comment by tsimeunovic** [comment]
just checked. selectors inside query are all in form
element.class (ie. div.dialog), no id selectors

**Comment by kennyt** [comment]
I actually cannot reproduce this problem on my end. Can I see your content/css?

Currently, it will remove IDs and html tags from the media queries (bug, not a feature), but classes should work

**Comment by kangw3n** [comment]
Tested, IDs and HTML @media will not work, but classes did working, hope IDs and html tags will be soon available 

btw while using classes's mediaquery, it will generate bunch of whitespacing on unminified version
