### ISSUE TITLE
Output removed CSS

### ISSUE THREAD

**Issue by ShaunYearStrong** [purifycss/purifycss#48]
I'd like an option to just show what would be removed instead of actually deleting it, allowing me to remove the rules myself from the source.

**Comment by astraldragon** [comment]
That was actually the first thing that came to mind when I thought of how I would use it.  I would like a preview to be able to see what is missing, because maybe the things that are going to be stripped out are actually supposed to be used.

**Comment by kennyt** [comment]
Interesting, I think adding this as an opt-in could be awesome. Will look into this.

**Comment by Illyism** [comment]
You can already do this with the `diff` tool in linux.

```
diff -y <(cat remove_unused.css) <(purifycss remove_unused.css remove_unused.js)
```

![2015-06-17-171110_663x265_scrot](https://cloud.githubusercontent.com/assets/304283/8210781/179a093c-1503-11e5-9498-b0f72cc332e4.png)

**Comment by ShaunYearStrong** [comment]
Accidental close there. 
That looks like a start, I think a log of some sort may be better, you've potentially got a lot of output.

**Comment by corysimmons** [comment]
:+1:

**Comment by unwitting** [comment]
The tool is really great, but I've gotta say this would make it actually useful. In our app the output CSS is a little smaller, but a diff is useless; many things are moved enough that the diff counts them as removed and then added further down. A clear output of the rules removed would be great.

**Comment by unwitting** [comment]
Can try putting together a PR if people are willing to take it? @kennyt?

**Comment by kennyt** [comment]
#62
