### ISSUE TITLE
AngularJS classes that aren't used immediately get removed

### ISSUE THREAD

**Issue by TejasQ** [purifycss/purifycss#66]
I understand that this could be a doozie to solve, but AngularJS does not add classes to certain elements until they are required to be animated, which is when it adds a whole bunch of classes (.ng-animate, .ng-enter, etc.). These get removed when the CSS gets purified.

Also, angular doesn't add elements to the DOM that have an ng-if directive until a certain condition is met. 

Perhaps there can be some type of whitelist of classes to never remove from a source css document?

Just a thought...

**Comment by Illyism** [comment]
+1 for a whitelist

Same issue in Semantic UI with transitions.

**Comment by kennyt** [comment]
A quick solution for this would be to leave a comment somewhere in a file that is being read. For example:
```
// ng-animate ng-enter
```
and it will get picked up. That should work.

**Comment by ingoe** [comment]
Same issue for this conditional in angular:
<div ng-class="{anotherClassname: true}" class="someClassname">
"anotherClassname" gets removed from the CSS after purifying.

**Comment by Enkil** [comment]
+1 with this issue for PurifyCss and AngularJS ng-show/ng-hide animations

**Comment by kennyt** [comment]
A whitelist feature is coming

**Comment by zaideygrek** [comment]
+1

**Comment by kennyt** [comment]
Whitelist feature published. It's an array in the options obj. [see here](https://github.com/purifycss/purifycss/blob/master/README.md#properties-of-options-object)
