### ISSUE TITLE
Single-quoted attribute selectors

### ISSUE THREAD

**Issue by gilly3** [purifycss/purifycss#72]
Attribute selectors using single quotes are removed.

```js
var purify = require("purify-css");

var html = '<form action="foo/"><button id="a">Go</button><input id="b" /></form>';
var css = "form[action='foo/'] #a, #b { display: none; }";

purify(html, css, console.log);
```

This logs `#b { display: none;}`, omitting the expected attribute selector.  I figured out eventually that changing my CSS to use double quotes corrects the problem, but single quotes ought to be supported.

**Comment by kennyt** [comment]
Should be good now, thanks
