### ISSUE TITLE
Do you plan to add LESS or SASS support? 

### ISSUE THREAD

**Issue by kolesnik** [purifycss/purifycss#74]

**Comment by jlukic** [comment]
Wouldnt you just want to purify the outputted css?

**Comment by kolesnik** [comment]
It's a long way because after it I have to convert back css to less/sass but it will work for me, is there are any others options ?

**Comment by jlukic** [comment]
If you are looking to track down stale rules in your LESS. You can probably accomplish this by using sourcemaps and comparing the difference in purified CSS.

**Comment by kolesnik** [comment]
Got it, thanks for help.

**Comment by jlukic** [comment]
Here's a good repo for [parsing source maps](https://github.com/mozilla/source-map) programmatically

**Comment by kolesnik** [comment]
Great!
