### ISSUE TITLE
Why not simply use Google Chrome's Audits feature?

### ISSUE THREAD

**Issue by santosh** [purifycss/purifycss#82]
What's the use of purifycss if same things can be done in Google Chrome's developer console's **Audits** tab? Pretty simple, isn't that?

It's not actually a issue; just asking.

**Comment by christoferd** [comment]
Google Audit tool does not create the slimmed down CSS file for you.
However, it would be great to be able to just paste the results from Google Audit into a page and have it export the new slim CSS :-)
