### ISSUE TITLE
Haml support

### ISSUE THREAD

**Issue by Maciekp** [purifycss/purifycss#84]
Hi,
does it support haml files( especially in RoR setup)?

**Comment by hebuliang** [comment]
I think it could since it scan all the files and extract all the words from those files, and it works on my RoR project which i used it to detect all the LESS files and html.erb files.

**Comment by andrewtpoe** [comment]
@hebuliang 

Can you explain how you plugged this tool into your RoR app? My Google foo fails me...

**Comment by kennyt** [comment]
Yes it supports haml, just pass the paths to the files into the `content` argument
