### ISSUE TITLE
Option for removing css comments

### ISSUE THREAD

**Issue by erlinghoff** [purifycss/purifycss#86]
I ran my code through purifycss, and it gave impressive results. However, I noticed that the css comments contained in the original files were preserved. Is there an option for removing these?

**Comment by Digikid13** [comment]
I'm not totally sure this is needed, you should be running the files through a mini-fier as well which should be removing the comments.

**Comment by kennyt** [comment]
You can set `minify` to `true` in the options in order to minify your CSS

**Comment by HugoDelval** [comment]
Sorry to reopen an old issue like this one, but it seems that setting `minify` to `true` does not remove comments starting with `/*!` 

Is it done on purpose? If so, would it be interesting to have an option to remove **all** comments of a file regardless how they are written? Something like `--min=force`

Thanks :)

**Comment by fastrer** [comment]
Sorry to reopen second time an old issue like this one, but it seems that setting minify to true does not remove comments starting with /*!

Is it done on purpose? If so, would it be interesting to have an option to remove all comments of a file regardless how they are written? Something like --min=force

Thanks :)

**Comment by ethaniel** [comment]
This problem still persists (`/*!` comments) with the online tool.
