### ISSUE TITLE
Pseudo elements not removed - fix not implemented

### ISSUE THREAD

**Issue by NeilJS** [purifycss/purifycss#91]
Hi. I have noticed that many css selectors are not removed, including css using pseudo selectors (such as `.glyphicon-asterisk:before {...}`), although a fix does exist.

Some info...

* I am using purifycss via `npm install purify-css` - version 1.0.17. This does not remove pseudo selectors.
* The master branch on github is actually a **different version**: version 1.0.8. This also  does not remove pseudo selectors (although it looks like there may have been an attempt to merge the following fix).
* Fix: https://github.com/purifycss/purifycss/issues/39 - I replaced my `src/sccTree.js` with this fix: https://github.com/purifycss/purifycss/blob/f45537378a8c236bd4ddca5f89d762b3e627ce23/src/cssTree.js and pseudo selectors *are* now removed successfully. Can this be worked back into the master and can the npm installer make use of this latest version?
* In my setup, purify-css is reducing file size by 1.3 times but there are still many Bootstrap styles that remain (and are not found in any of my source templates); such as `.progress-bar`. Anybody else had this?

Thanks

**Comment by korvus** [comment]
relative to the same issue, had to replace my sccTree.js + purifycss.js with latest github version instead npm official one, because of the "rejected" option not working properly with npm depository version despite it's show on into documentation.

Made a minor request for that, by implementing comments (sorry for didn't put any coments...): https://github.com/purifycss/purifycss/compare/master...korvus:patch-1

**Comment by IngwiePhoenix** [comment]
I can see this behavior too. Please port the above mentioned fix from #39 into the NPM version.

**Comment by IngwiePhoenix** [comment]
Here is a dump of a CSS that went through Purify.

https://gist.github.com/IngwiePhoenix/b527fba0b888614cf46e

Basically I made this using my version of the webpack plugin. There are no files being run though Purify _at all_. This is what happens with a blank file list - aka. `[]`.

Minified, this is still 30kb. My normal build is 74kb. Taking away some of the non-pseudo selectors, such as seen on the audio element, I bet it would go down to 50kb.

It feels neccessary that this issue gets dealt with. o.o

**Comment by roxkisrover** [comment]
I agree. It is weird to see `.row` selector removed and `.row:before` or `.row:after` left untouched.

**Comment by kennyt** [comment]
#107 fixed this
