### ISSUE TITLE
Compatibility to class-naming

### ISSUE THREAD

**Issue by IngwiePhoenix** [purifycss/purifycss#93]
In my app I was previously using EJS, but once I had discovered [jsxr](http://npmjs.org/jsxr), i threw that over and I am now migrating to that instead.

However, I have noticed that the size of my CSS is rather big still. I know that my app does not use most of the Bootstrap (3.3.x) stuff, and yet:

```
##################################
Before purify, CSS was 97033 chars long.
After purify, CSS is 54440 chars long. (1.7 times smaller)
##################################
This function took:  402 ms
```

The actual views are rendered through PHP, so sometimes I have a syntax like:

```php
<?=HTML::image("... some source ...", ["class"=>"thumbnail"])?>
```

And in JSX,
```jsx
var img = (<img
  src={source}
  className="thumbnail"
/>);
```

And EJS is your standard HTML with JS mixed in.

So I wanted to ask which kinds of "syntaxes" PurifyCSS reads and understands?

**Comment by kennyt** [comment]
PurifyCSS will actually be able to read anything. Even a README.md file if you really wanted. It treats everything as a string, and looks at the words that come up inside of that string. The downside to this approach is that there can be a lot of noise (words that come up in the files, but don't actually get used towards a class), which results in extra selectors in the purified CSS file.

There is a special optimization for JS files, which reduces a lot of noise. But if you're passing in a file that's not pure JS, it will inherently be less efficient
