### ISSUE TITLE
Output css formatting is wrong when the first selector in a comma list is removed

### ISSUE THREAD

**Issue by madsgodvinjensen** [purifycss/purifycss#97]
If you have the following declared in your css:

```
.unused-class-name, h1, p {
    color: red;
}
```

It ends up like this in the ouput:

```
, h1, p {
    color: red;
}
```
... which doesn't really work. The comma that belongs to the removed selector is not removed. So, similarly, "h1, .unused-class-name, p" ends up as "h1,, p".

This is a fairly new issue. Definitely from some of the recent commits (January 2016).

**Comment by kennyt** [comment]
Ah yes, I see it now. PR #80 breaks this. I just put in a fix

**Comment by madsgodvinjensen** [comment]
Cool. Thank you very much for the fast response.
